### ISSUE TITLE
Partials?

### ISSUE THREAD

**Issue by jontonsoup** [rstacruz/exslim#4]
https://github.com/nurugger07/calliope does not support partials. Does expug? I didn't see anything in the docs. 

Thanks!

**Comment by jontonsoup** [comment]
Never mind -- answer is no.

**Comment by rstacruz** [comment]
Expug is mostly useful with phoenix at the moment, which supports partials.
What does your stack look like?

**Comment by jontonsoup** [comment]
Maybe I’m confused between a phoenix partial and an expug partial?

It seems in the docs its not implemented, but maybe phoenix partials are macros?

**Comment by rstacruz** [comment]
In Phoenix, partials are done this way:

```
= render MyApp.MyView, "mypartial.html"
```

The Phoenix guides should have more info about this. With this, it makes
little sense for template engines to implement their own partial/layout
solution.

On that note, are you using phoenix or another framework of sorts?

**Comment by jontonsoup** [comment]
Phoenix, but rather new to it. This covers my needs! 

Best,

Jon
