### ISSUE TITLE
Compilation error on consecutive if else blocks

### ISSUE THREAD

**Issue by riacataquian** [rstacruz/exslim#6]
This causes a compilation error:
```
= if true do
  p ...
= else
  p ...

= if true do
  p ...
= else
  p ...
```

However, these cases work:
 - Adding an extra element between if else blocks
```
= if true do
  p ...
= else
  p ...

span Unnecessary element

= if true do
  p ...
= else
  p ...
```

- Consecutive if blocks

```
= if true do
  p ...

= if true do
  p ...
```

**Comment by rstacruz** [comment]
Fixed in 0.8.0! 💚 💛 Thanks for the report. Update your expug:

```sh
mix deps.update expug
```

![image](https://cloud.githubusercontent.com/assets/74385/23889942/7e839c50-08ca-11e7-909e-b807187ff40f.png)

https://try-expug.herokuapp.com/
