### ISSUE TITLE
Compilation errors when using `$`

### ISSUE THREAD

**Issue by cubeguerrero** [rstacruz/exslim#7]
Use case
```
render "_some_view.html", title: "$ Title"
```

Error Message
<img width="888" alt="screen shot 2017-03-14 at 2 47 08 pm" src="https://cloud.githubusercontent.com/assets/3756584/23888886/2181bd20-08c5-11e7-8b13-969ec4104745.png">

**Comment by rstacruz** [comment]
help me fix iiittt

**Comment by rstacruz** [comment]
is that the only thing that triggers it? because I really doubt that. `"Expug encountered a character it didn't expect."` is a parse error in parsing an Expug source. Most likely your problem lies in the `.pug` file. :)

**Comment by rstacruz** [comment]
Also there should be something above that line. It usually looks like this:

```
    Parse error on line 2

        div<color=@blue>
           ^

    Expug encountered a character it didn't expect.
```

**Comment by marksteve** [comment]
@fatbotdesigns @rstacruz Prolly has to do with "$". Hit this when I was doing: `div $100`
